baseURL: "https://example.com"

module:
  imports:
    - path: github.com/peaceiris/hugo-theme-iris

# googleAnalytics: UA-123-45
disqusShortname: hugothemeiris

# paginate: 3
canonifyURLs: true
enableRobotsTXT: true
pluralizeListTitles: false

# hugo syntax highlighting
pygmentsUseClasses: true
pygmentsCodefences: true

enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true

taxonomies: {}
#   - tag: tags

imaging:
  quality: 75

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
  tdewolff:
    xml:
      keepWhitespace: true

# Configure Languages
DefaultContentLanguage: en
languages:
  en:
    contentDir: content/en
    languageName: English
    languageCode: en-us
    params:
      author: USERNAME
      description: Hugo IRIS Theme Demo Site
      publishdate: '2020-01-01'
      twitter:
        username: piris314
      ogp:
        siteName: Hugo Demo Site
        image: images/ogp.jpg
        locale: en-US
    title: Hugo Demo Site
    weight: 1
